### ISSUE TITLE
IR Question

### ISSUE THREAD

**Issue by Crsarmv7l** [d03n3rfr1tz3/TTGO.T-Watch.2020#15]
Hi,

Looking for some insight about your IR Remote app included in Sharandac's firmware.

I have 3 TV's in my house, and for simplicity sake I would like to create one remote that sends 3 commands (one for each tv) with each button press. Think the old school tv-b-gone. That would simplify the interface/remotes, reducing it to one remote on screen, which should work on 3 different tvs. Not the most elegant, but effective.

The remote file would look like this:

`{
    "Remote": [{
            "Power": {
                "m": 7,
                "hex": "E0E040BF"
                "m": tv2,
                "hex": "tv2 hex"
                "m": tv3,
                "hex": "tv3 hex"
            },
            "Ch+": {
                "m": 7,
                "hex": "E0E048B7"
                "m": tv2,
                "hex": "tv2 hex"
                "m": tv3,
                "hex": "tv3 hex"
            },
            "Ch-": {
                "m": 7,
                "hex": "E0E008F7"
                "m": tv2,
                "hex": "tv2 hex"
                "m": tv3,
                "hex": "tv3 hex"
                       }    .........
        }
    ],
    "defBtnHeight": 33,
    "defBtnWidth": 65,
    "defSpacing": 2
}
`

Obviously the "m" and hex values would be replaced by the appropriate values.

I haven't yet looked at the source for the app, just wanted to know if this is feasible, and if not, can you provide a little insight on how your app functions?

**Comment by d03n3rfr1tz3** [comment]
First off, I have to say, that I did not write the IR Remote app. I just added support for multiple pages. But I think I can still help you.
Currently the app can only send one command for each button. Therefore your JSON definition would not work and would probably even lead to an error, depending on how strict the deserializer handles that.

You have multiple problems in your JSON, that will not work. The first is the property "Remote", which needs to be "pages". If you only need one page, that is ok, but this property cannot be renamed. So the whole thing should look like this.

`{ "pages": [{ ... }] }`

The second problem is your definition of each button. I know you tried to define multiple commands for one button, but that is not possible. The property name is used as the button name and the content if it configures that button. Your "Power" button has multiple "m" and multiple "hex" definitions, which would not work. You need to split them into separate buttons. It would look like this.

`... { "Power1": { "m": 7, "hex": "ABCDEF" }, "Power2": { "m": 7, "hex": "ABCDEF" }, "Power3": { "m": 7, "hex": "ABCDEF" } } ...`

So a definition for multiple commands, if this support gets added to the app, would probably change the object in the value for each button to an array. Just an example of how it could look, but beware that this is currently not implemented and just an idea of how it could be done in the future.

`... { "Power": [{ "m": 7, "hex": "ABCDEF" }, { "m": 7, "hex": "ABCDEF" }, { "m": 7, "hex": "ABCDEF" }] } ...`

For now I can only suggest, that you create three identical remotes as three separate pages. You would have to slide to the correct page, but at least you would have your three remotes for now.

**Comment by Crsarmv7l** [comment]
Thanks again for the reply. I sorted my json issues a few days ago and saw the need for "pages" in the app code as well as the max button size constraints. Trial and error showed multiple commands on a single button doesn't work 🤣 

I have written my current json for multiple remotes/pages, just hoping to simplify things a bit in the future.

**Comment by d03n3rfr1tz3** [comment]
Be aware, it is only merged into my master-branch. I'm about to create the PR to merge the same changes into sharandacs master-branch, which is the real firmware IMO.

**Comment by Crsarmv7l** [comment]
Awesome! Thank you so much, definitely didn't expect you to get to it any time soon. I know how dev on fun stuff goes. I am building against a pretty hacked up version of sharandac's oct code in order to get it working with Sailfish OS, so I will probably end up cherry picking your code into my current stuff.

I haven't looked through your commits yet but how did you end up structuring the json to account for multiple transmissions on one button, as an array?

Thanks again, I appreciate your work on this enhancement.

**Comment by d03n3rfr1tz3** [comment]
I also added an example at the bottom of the IR example config. Maybe that helps.
https://github.com/d03n3rfr1tz3/TTGO.T-Watch.2020/blob/master/conf/ir-remote.json.example

The code itself just checks if there is an object or an array present and initializes a button with one or multiple commands. On pressing the button it iterates through the commands with an 100 milliseconds pause. It surprisingly worked very well on my watch and powered on and off my TV, BluRay and AudioDecoder at the same time.

I personall do not need it, because I have separate pages for each remote, but I thought and still think this is a very useful feature, which is why I wanted it to not move it too far in the future.
