### ISSUE TITLE
Delay before IR Send

### ISSUE THREAD

**Issue by Crsarmv7l** [d03n3rfr1tz3/TTGO.T-Watch.2020#19]
Once again thank you for the multicommand for IR.

For my own use case I would like to introduce a delay before sending the IR code.That way I can directly look at the screen, press the button, then twist my wrist to point at the tv.

 Looking through the IRController.cpp, would this be the appropriate place, and way to do so? I see further down the execute_ir_cmd ties in with irsend.

`Button btn(button);
                    btn.size(irConfig.defBtnWidth, irConfig.defBtnHeight);
                    btn.text(btnConfig->name);
                    btn.clicked([btnConfig](Widget& btn) { 
                        delay(2000)
                        execute_ir_cmd(btnConfig);
                    });`

**Comment by d03n3rfr1tz3** [comment]
Spontaneous I would say, that should do the trick.
Maybe just have a look, if the UI gets blocked or something strange is happening (like loosing WiFi connection). If yes, it might be necessary to manually create a separate task and do the delay + command in there to not block other relevant things. If no, than it already is a separate task and everything is fine.

**Comment by Crsarmv7l** [comment]
Worked like a charm (I also a ; in the code, which I forgot above). Thanks for all your help!

Hopefully my json isn't too big, since I have a couple remotes and a multi-remote as well!
